# Generated by Django 4.2.10 on 2024-03-01 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='data_de_criação',
            new_name='data_de_criacao',
        ),
    ]
